170/accessibility
graasp/graasp-library pull request #171
Opened 2022-07-25 11:15 UTC by xiaotiansu

- more descriptive aria labels
- access button groups with only keyboards

2022-07-26 13:00 UTC, pyphilia requested changes
Nice changes! I'm actually thinking of translating the `alt` properties, I guess it's necessary for multi-language accessibility, what do you think?

2022-07-26 13:41 UTC, xiaotiansu commented on src/components/layout/UserHeader.js
> +        alt={`${{ username }}'s avatar`}
I have some new pushes, but I can't see it on Github, not sure about your side.

2022-07-27 15:24 UTC, pyphilia requested changes
I've added 2-3 minor comments 🐰

2022-07-27 15:24 UTC, pyphilia commented on src/components/home/Search.js
> +          aria-label="search button"
Does this need a translation? Not sure what aria-label does^^

2022-07-27 15:24 UTC, pyphilia commented on src/components/collection/Authorship.js
> +                  alt={t(`${authorName}'s avatar`)}
What you could do is using variables! https://www.i18next.com/translation-function/interpolation

2022-07-27 15:24 UTC, pyphilia commented on src/langs/fr.json
> +    "'s avatar": "de l'avatar"
It's actually the inverse x'3 `Avatar de x`

2022-08-03 08:49 UTC, pyphilia requested changes
Looks good to me, did you take a look at the card we discussed last time? Did you manage to navigate to the image or do we need to add a view button?

2022-08-03 08:49 UTC, pyphilia commented on src/langs/fr.json
> +    "someone's avatar": "Avatar de {{name}}",
The fr and en files are not symmetric, I think you miss some translations in both files.

2022-08-11 07:11 UTC, pyphilia approved these changes

2022-08-11 07:12 UTC, merged