feat!: remove immutable
graasp/graasp-library pull request #413
Opened 2023-11-01 13:54 UTC by pyphilia

2023-11-02 18:01 UTC, spaenleh requested changes

2023-11-03 08:47 UTC, pyphilia commented on src/components/collection/ItemBreadcrumb.tsx
>    }
Or we use `useParents` that does all the computation for us?

2023-11-03 09:29 UTC, spaenleh commented on src/components/collection/ItemBreadcrumb.tsx
>    }
Yes !

2023-11-03 17:34 UTC, spaenleh approved these changes
🚀 ⛵

2023-11-06 12:29 UTC, merged